// Databank v2 — per-kind configuration: columns, facets, numeric ranges, search fields, radar axes.
// Every column: { key, label, get(row, ctx), type: 'num'|'text'|'enum'|'list'|'pct'|'bool', unit, dec, heat (shade by max), width, on (default visible) }
import { Crosshair, Ship, RadarIcon, FlaskConical, Boxes, Shapes, Compass } from "lucide-react";
import { countIds } from "@/lib/gameData";

const num = (v) => (typeof v === "number" && Number.isFinite(v) ? v : null);
const listNames = (ids, ctx) => countIds(ids || []).map(([id, n]) => `${n > 1 ? n + "× " : ""}${ctx.byId[id]?.name || id}`).join(", ");
const energy = (r) => (num(r.energy_production) ? num(r.energy_production) : -(num(r.energy_per_second) || 0)) || 0;

const common = [
  { key: "name", label: "Name", get: (r) => r.name, type: "text", width: 240, on: true, sticky: true },
  { key: "game_id", label: "ID", get: (r) => r.game_id, type: "text", width: 90, on: false },
  { key: "tier", label: "Tier", get: (r) => num(r.tier), type: "num", dec: 0, width: 60, on: true },
];

export const KINDS = {
  Module: {
    label: "Modules", icon: Boxes, rows: (cat) => cat.modules, groupBy: "module_class",
    facets: [["module_class", "Class"], ["module_type", "Type"], ["module_sub_type", "Sub-type"], ["weapon_category", "Weapon cat."], ["tier", "Tier"], ["agent_category", "AI role"], ["mount_size", "Mount"]],
    ranges: ["cost_resources", "max_health", "armor", "dps_total", "energy", "cost_population", "mass", "construction_time"],
    search: ["name", "game_id", "info", "description", "module_type", "module_sub_type", "module_class"],
    radar: [["dps_total", "DPS"], ["max_health", "HP"], ["armor", "Armor"], ["cost_resources", "Cost", true], ["energy", "Energy"], ["visual_range", "Vision"], ["cargo_capacity", "Cargo"]],
    columns: [
      ...common,
      { key: "module_class", label: "Class", get: (r) => r.module_class, type: "enum", width: 100, on: true },
      { key: "module_type", label: "Type", get: (r) => r.module_type, type: "enum", width: 120, on: true },
      { key: "module_sub_type", label: "Sub-type", get: (r) => r.module_sub_type, type: "enum", width: 130, on: false },
      { key: "cost_resources", label: "Cost", get: (r) => num(r.cost_resources), type: "num", dec: 0, unit: "RU", heat: true, width: 90, on: true },
      { key: "cost_population", label: "Crew", get: (r) => num(r.cost_population), type: "num", dec: 0, heat: true, width: 70, on: true },
      { key: "construction_time", label: "Build", get: (r) => num(r.construction_time), type: "num", dec: 0, unit: "s", width: 70, on: false },
      { key: "max_health", label: "HP", get: (r) => num(r.max_health), type: "num", dec: 0, heat: true, width: 80, on: true },
      { key: "armor", label: "Armor", get: (r) => num(r.armor), type: "num", dec: 0, heat: true, width: 70, on: true },
      { key: "energy", label: "Energy/s", get: energy, type: "num", dec: 1, signed: true, width: 80, on: true },
      { key: "dps_total", label: "DPS", get: (r) => num(r.dps_total), type: "num", dec: 1, heat: true, width: 80, on: true },
      { key: "mass", label: "Mass", get: (r) => num(r.mass), type: "num", dec: 0, width: 70, on: false },
      { key: "cargo_capacity", label: "Cargo", get: (r) => num(r.cargo_capacity), type: "num", dec: 0, width: 80, on: false },
      { key: "extraction_rate", label: "Extract", get: (r) => num(r.extraction_rate), type: "num", dec: 1, width: 80, on: false },
      { key: "resource_production", label: "Prod/s", get: (r) => num(r.resource_production), type: "num", dec: 2, width: 80, on: false },
      { key: "visual_range", label: "Vision", get: (r) => num(r.visual_range), type: "num", dec: 0, width: 70, on: false },
      { key: "sensors_range", label: "Sensors", get: (r) => num(r.sensors_range), type: "num", dec: 0, width: 80, on: false },
      { key: "mount_size", label: "Mount", get: (r) => num(r.mount_size), type: "num", dec: 0, width: 60, on: false },
      { key: "weapons", label: "Armament", get: (r, ctx) => listNames(r.weapons, ctx), type: "list", width: 240, on: true },
      { key: "required_research", label: "Research", get: (r, ctx) => listNames(r.required_research, ctx), type: "list", width: 200, on: false },
      { key: "score", label: "Score", get: (r) => num(r.score), type: "num", dec: 0, width: 70, on: false },
      { key: "agent_category", label: "AI role", get: (r) => r.agent_category, type: "enum", width: 110, on: false },
      { key: "work_in_progress", label: "WIP", get: (r) => !!r.work_in_progress, type: "bool", width: 50, on: false },
    ],
  },
  Unit: {
    label: "Ships", icon: Ship, rows: (cat) => cat.units, groupBy: "unit_class",
    facets: [["unit_class", "Class"], ["unit_type", "Type"], ["faction", "Faction"], ["tier", "Tier"], ["default_style", "Style"], ["default_stance", "Stance"]],
    ranges: ["cost_resources", "max_health", "armor", "max_speed", "dps_total", "cost_population", "mass", "cargo_capacity"],
    search: ["name", "game_id", "info", "description", "unit_class", "unit_type", "faction"],
    radar: [["dps_total", "DPS"], ["max_health", "HP"], ["armor", "Armor"], ["max_speed", "Speed"], ["cost_resources", "Cost", true], ["visual_range", "Vision"], ["cargo_capacity", "Cargo"]],
    columns: [
      ...common,
      { key: "faction", label: "Faction", get: (r) => r.faction || (String(r.game_id).startsWith("PIR") ? "PIR" : "CMX"), type: "enum", width: 70, on: true },
      { key: "unit_class", label: "Class", get: (r) => r.unit_class, type: "enum", width: 90, on: true },
      { key: "unit_type", label: "Type", get: (r) => r.unit_type, type: "enum", width: 120, on: false },
      { key: "cost_resources", label: "Cost", get: (r) => num(r.cost_resources), type: "num", dec: 0, unit: "RU", heat: true, width: 90, on: true },
      { key: "cost_population", label: "Crew", get: (r) => num(r.cost_population), type: "num", dec: 0, width: 70, on: true },
      { key: "max_health", label: "HP", get: (r) => num(r.max_health), type: "num", dec: 0, heat: true, width: 80, on: true },
      { key: "armor", label: "Armor", get: (r) => num(r.armor), type: "num", dec: 0, heat: true, width: 70, on: true },
      { key: "max_speed", label: "Speed", get: (r) => num(r.max_speed), type: "num", dec: 2, heat: true, width: 70, on: true },
      { key: "turning_power", label: "Turn", get: (r) => num(r.turning_power), type: "num", dec: 2, width: 60, on: false },
      { key: "dps_total", label: "DPS", get: (r) => num(r.dps_total), type: "num", dec: 1, heat: true, width: 80, on: true },
      { key: "weapons", label: "Fixed armament", get: (r, ctx) => listNames(r.weapons, ctx), type: "list", width: 200, on: true },
      { key: "hardpoints", label: "Hardpoints", get: (r) => Object.entries(r.hardpoints || {}).map(([k, v]) => `${v} ${k}`).join(", "), type: "text", width: 130, on: true },
      { key: "secondary_equip", label: "Default fit", get: (r, ctx) => [r.primary_equip, r.secondary_equip].filter(Boolean).map((id) => ctx.byId[id]?.name || id).join(" · "), type: "text", width: 200, on: false },
      { key: "default_stance", label: "Stance", get: (r) => r.default_stance, type: "enum", width: 90, on: false },
      { key: "default_style", label: "Style", get: (r) => r.default_style, type: "enum", width: 80, on: false },
      { key: "enabled_styles", label: "Styles", get: (r) => r.enabled_styles, type: "enum", width: 140, on: false },
      { key: "visual_range", label: "Vision", get: (r) => num(r.visual_range), type: "num", dec: 0, width: 70, on: false },
      { key: "cloak_strength", label: "Cloak", get: (r) => num(r.cloak_strength), type: "num", dec: 2, width: 60, on: false },
      { key: "cargo_capacity", label: "Cargo", get: (r) => num(r.cargo_capacity), type: "num", dec: 0, width: 80, on: false },
      { key: "mass", label: "Mass", get: (r) => num(r.mass), type: "num", dec: 1, width: 70, on: false },
      { key: "levels", label: "Vet. levels", get: (r) => (r.levels || []).length, type: "num", dec: 0, width: 80, on: false },
      { key: "required_research", label: "Research", get: (r, ctx) => listNames(r.required_research, ctx), type: "list", width: 200, on: false },
      { key: "score", label: "Score", get: (r) => num(r.score), type: "num", dec: 0, width: 70, on: false },
    ],
  },
  Weapon: {
    label: "Weapons", icon: Crosshair, rows: (cat) => cat.weapons, groupBy: "weapon_type",
    facets: [["weapon_type", "Type"], ["implementation", "Impl."], ["requires_reload", "Reload"], ["single_shot", "Single shot"], ["applied_status_on_hit", "Status"]],
    ranges: ["dps", "range", "hp_change", "armor_penetration", "rate_of_fire", "bullet_speed", "burst_amount", "reload_time"],
    search: ["name", "game_id", "description", "weapon_type", "implementation"],
    radar: [["dps", "DPS"], ["range", "Range"], ["hp_change", "Hull/hit"], ["armor_penetration", "Armor pen"], ["rate_of_fire", "RoF"], ["bullet_speed", "Speed"]],
    columns: [
      ...common.filter((c) => c.key !== "tier"),
      { key: "weapon_type", label: "Type", get: (r) => r.weapon_type, type: "enum", width: 110, on: true },
      { key: "implementation", label: "Impl.", get: (r) => r.implementation, type: "enum", width: 100, on: false },
      { key: "dps", label: "DPS", get: (r) => num(r.dps), type: "num", dec: 1, heat: true, width: 80, on: true },
      { key: "range", label: "Range", get: (r) => num(r.range), type: "num", dec: 1, heat: true, width: 80, on: true },
      { key: "hp_change", label: "Hull/hit", get: (r) => num(r.hp_change), type: "num", dec: 2, heat: true, width: 80, on: true },
      { key: "shield_change", label: "Shield/hit", get: (r) => num(r.shield_change), type: "num", dec: 2, width: 80, on: false },
      { key: "armor_penetration", label: "Armor pen", get: (r) => num(r.armor_penetration), type: "pct", dec: 0, heat: true, width: 90, on: true },
      { key: "rate_of_fire", label: "RoF", get: (r) => num(r.rate_of_fire), type: "num", dec: 2, unit: "/s", width: 70, on: true },
      { key: "burst_amount", label: "Burst", get: (r) => num(r.burst_amount), type: "num", dec: 0, width: 60, on: false },
      { key: "burst_interval", label: "Burst int.", get: (r) => num(r.burst_interval), type: "num", dec: 2, unit: "s", width: 80, on: false },
      { key: "reload_time", label: "Reload", get: (r) => (r.requires_reload ? num(r.reload_time) : null), type: "num", dec: 1, unit: "s", width: 70, on: false },
      { key: "bullet_speed", label: "Proj. speed", get: (r) => num(r.bullet_speed), type: "num", dec: 1, width: 90, on: false },
      { key: "bullet_lifetime", label: "Lifetime", get: (r) => num(r.bullet_lifetime), type: "num", dec: 1, unit: "s", width: 80, on: false },
      { key: "area_radius", label: "AoE r", get: (r) => (r.deal_area_damage ? num(r.area_radius) : null), type: "num", dec: 1, width: 70, on: false },
      { key: "class_damage_multipliers", label: "Class mult.", get: (r) => (r.class_damage_multipliers || []).map((m) => `${m.entity_class} ×${m.multiplier}`).join(", "), type: "list", width: 220, on: true },
      { key: "applied_status_on_hit", label: "Status", get: (r) => r.applied_status_on_hit, type: "enum", width: 80, on: false },
      { key: "cost_resources", label: "Cost", get: (r) => num(r.cost_resources), type: "num", dec: 0, width: 80, on: false },
      { key: "required_research", label: "Research", get: (r, ctx) => listNames(r.required_research, ctx), type: "list", width: 200, on: false },
    ],
  },
  Turret: {
    label: "Turrets", icon: RadarIcon, rows: (cat) => cat.turrets, groupBy: null,
    facets: [["is_fixed", "Fixed"], ["weapons_count", "Guns"], ["weapons_source", "Source"]],
    ranges: ["dps_total", "cost_resources", "horizontal_rotation_speed", "time_between_volleys", "weapons_count"],
    search: ["name", "game_id", "description"],
    radar: [["dps_total", "DPS"], ["horizontal_rotation_speed", "Rotation"], ["cost_resources", "Cost", true], ["weapons_count", "Guns"]],
    columns: [
      ...common.filter((c) => c.key !== "tier"),
      { key: "weapons", label: "Weapons", get: (r, ctx) => listNames(r.weapons, ctx), type: "list", width: 220, on: true },
      { key: "weapons_count", label: "Guns", get: (r) => num(r.weapons_count), type: "num", dec: 0, width: 60, on: true },
      { key: "dps_total", label: "DPS", get: (r) => num(r.dps_total), type: "num", dec: 1, heat: true, width: 80, on: true },
      { key: "cost_resources", label: "Cost", get: (r) => num(r.cost_resources), type: "num", dec: 0, heat: true, width: 80, on: true },
      { key: "construction_time", label: "Build", get: (r) => num(r.construction_time), type: "num", dec: 0, unit: "s", width: 70, on: false },
      { key: "horizontal_rotation_speed", label: "Rotation", get: (r) => num(r.horizontal_rotation_speed), type: "num", dec: 0, unit: "°/s", width: 90, on: true },
      { key: "horizontal_fov", label: "H-FOV", get: (r) => (r.horizontal_fov ? `${r.horizontal_fov[0]}…${r.horizontal_fov[1]}` : null), type: "text", width: 100, on: false },
      { key: "time_between_volleys", label: "Volley", get: (r) => num(r.time_between_volleys), type: "num", dec: 1, unit: "s", width: 70, on: true },
      { key: "time_between_weapon_shots", label: "Shot gap", get: (r) => num(r.time_between_weapon_shots), type: "num", dec: 2, unit: "s", width: 80, on: false },
      { key: "is_fixed", label: "Fixed", get: (r) => !!r.is_fixed, type: "bool", width: 60, on: true },
      { key: "predictive_aim", label: "Pred. aim", get: (r) => !!r.predictive_aim, type: "bool", width: 80, on: false },
      { key: "attack_priority", label: "Targets", get: (r) => (r.attack_priority || []).join(" › "), type: "list", width: 240, on: false },
      { key: "required_research", label: "Research", get: (r, ctx) => listNames(r.required_research, ctx), type: "list", width: 200, on: false },
    ],
  },
  ResearchNode: {
    label: "Research", icon: FlaskConical, rows: (cat) => cat.research, groupBy: "research_type",
    facets: [["research_type", "Type"], ["tier", "Tier"], ["implementation_mode", "Scope"], ["unit_class_affected", "Unit class"], ["module_class_affected", "Module class"], ["tree_depth", "Depth"]],
    ranges: ["cost_resources", "cost_energy", "construction_time", "tree_depth", "score"],
    search: ["name", "game_id", "info", "description", "research_type"],
    radar: [["cost_resources", "Cost", true], ["construction_time", "Time", true], ["tier", "Tier"], ["score", "Score"]],
    columns: [
      ...common,
      { key: "research_type", label: "Type", get: (r) => r.research_type, type: "enum", width: 100, on: true },
      { key: "cost_resources", label: "Cost", get: (r) => num(r.cost_resources), type: "num", dec: 0, unit: "RU", heat: true, width: 90, on: true },
      { key: "cost_energy", label: "Energy", get: (r) => num(r.cost_energy), type: "num", dec: 0, width: 70, on: false },
      { key: "construction_time", label: "Time", get: (r) => num(r.construction_time), type: "num", dec: 0, unit: "s", heat: true, width: 70, on: true },
      { key: "tree_depth", label: "Depth", get: (r) => num(r.tree_depth), type: "num", dec: 0, width: 60, on: true },
      { key: "modifiers", label: "Grants", get: (r) => (r.modifiers || []).map((m) => `${m.stat} ${m.operation === "Subtract" ? "−" : "+"}${Math.round((m.value || 0) * (m.abs ? 1 : 100))}${m.abs ? "" : "%"}`).join(", "), type: "list", width: 240, on: true },
      { key: "unlocks", label: "Unlocks", get: (r, ctx) => listNames([...(r.unlocks_modules || []), ...(r.unlocks_units || []), ...(r.unlocks_weapons || []), ...(r.unlocks || [])], ctx), type: "list", width: 220, on: true },
      { key: "required_nodes", label: "Requires", get: (r, ctx) => listNames(r.required_nodes, ctx), type: "list", width: 200, on: false },
      { key: "child_nodes", label: "Leads to", get: (r, ctx) => listNames(r.child_nodes, ctx), type: "list", width: 200, on: false },
      { key: "unit_class_affected", label: "Unit class", get: (r) => r.unit_class_affected, type: "enum", width: 100, on: false },
      { key: "module_class_affected", label: "Module class", get: (r) => r.module_class_affected, type: "enum", width: 110, on: false },
      { key: "score", label: "Score", get: (r) => num(r.score), type: "num", dec: 0, width: 70, on: false },
    ],
  },
  Doctrine: {
    label: "Doctrine", icon: Compass, rows: (cat) => [...(cat.combatTemplates || []).map((c) => ({ ...c, doctrine_kind: c.kind })), ...(cat.formations || []).map((f) => ({ ...f, doctrine_kind: "Formation" }))],
    groupBy: "doctrine_kind", facets: [["doctrine_kind", "Kind"]], ranges: [], search: ["name", "game_id", "doctrine_kind"], radar: [],
    columns: [
      { key: "name", label: "Name", get: (r) => r.name, type: "text", width: 220, on: true, sticky: true },
      { key: "game_id", label: "ID", get: (r) => r.game_id, type: "text", width: 160, on: false },
      { key: "doctrine_kind", label: "Kind", get: (r) => r.doctrine_kind, type: "enum", width: 100, on: true },
      { key: "modifiers", label: "Effects", get: (r) => (r.modifiers || []).map((m) => `${m.stat} ${m.operation === "Subtract" ? "−" : m.operation === "Set" ? "= " : "+"}${m.operation === "Set" || m.abs ? m.value : Math.round((m.value || 0) * 100) + "%"}`).join(", "), type: "list", width: 520, on: true },
      { key: "n", label: "#", get: (r) => (r.modifiers || []).length, type: "num", dec: 0, width: 50, on: true },
    ],
  },
  GameBlueprint: {
    label: "Blueprints", icon: Shapes, rows: (cat) => cat.blueprints || [], groupBy: "source",
    facets: [["source", "Source"], ["folder", "Folder"]],
    ranges: ["part_count", "sum_module_cost_resources", "dps_total", "sum_module_max_health", "crew_total", "construction_time"],
    search: ["name", "game_id", "folder"],
    radar: [["dps_total", "DPS"], ["sum_module_max_health", "HP"], ["sum_module_cost_resources", "Cost", true], ["part_count", "Parts"], ["crew_total", "Crew", true]],
    columns: [
      { key: "name", label: "Name", get: (r) => r.name, type: "text", width: 220, on: true, sticky: true },
      { key: "source", label: "Source", get: (r) => r.source, type: "enum", width: 80, on: true },
      { key: "folder", label: "Folder", get: (r) => r.folder || "—", type: "enum", width: 150, on: false },
      { key: "part_count", label: "Parts", get: (r) => num(r.part_count), type: "num", dec: 0, heat: true, width: 70, on: true },
      { key: "sum_module_cost_resources", label: "Cost", get: (r) => num(r.sum_module_cost_resources), type: "num", dec: 0, unit: "RU", heat: true, width: 100, on: true },
      { key: "crew_total", label: "Crew", get: (r) => num(r.crew_total), type: "num", dec: 0, width: 70, on: true },
      { key: "sum_module_max_health", label: "HP", get: (r) => num(r.sum_module_max_health), type: "num", dec: 0, heat: true, width: 90, on: true },
      { key: "dps_total", label: "DPS", get: (r) => num(r.dps_total), type: "num", dec: 1, heat: true, width: 80, on: true },
      { key: "energy", label: "Energy/s", get: (r) => (num(r.energy_production) || 0) - (num(r.energy_use) || 0), type: "num", dec: 1, signed: true, width: 80, on: true },
      { key: "construction_time", label: "Build", get: (r) => num(r.construction_time), type: "num", dec: 0, unit: "s", width: 70, on: false },
      { key: "weapon_modules", label: "Weapon modules", get: (r, ctx) => listNames(r.weapon_modules, ctx), type: "list", width: 240, on: true },
      { key: "required_research", label: "Research", get: (r, ctx) => listNames(r.required_research, ctx), type: "list", width: 200, on: false },
      { key: "assembly_depth", label: "Depth", get: (r) => num(r.assembly_depth), type: "num", dec: 0, width: 60, on: false },
    ],
  },
};

export const KIND_KEYS = Object.keys(KINDS);
export const CLASSES = ["FighterUnit", "CorvetteUnit", "FrigateUnit", "UtilityUnit", "PlatformUnit", "MineUnit", "CommandModule", "StructuralModule", "WeaponModule", "FacilityModule", "UtilityModule", "Station", "Wreckage"];

// Field aliases for the query language: alias -> column key
export const ALIASES = {
  class: ["module_class", "unit_class", "doctrine_kind"], type: ["module_type", "unit_type", "weapon_type", "research_type"], sub: ["module_sub_type"],
  cost: ["cost_resources", "sum_module_cost_resources"], hp: ["max_health", "sum_module_max_health"], health: ["max_health"], dps: ["dps_total", "dps"], range: ["range", "visual_range"],
  speed: ["max_speed", "bullet_speed"], crew: ["cost_population", "crew_total"], energy: ["energy"], armor: ["armor"], pen: ["armor_penetration"], rof: ["rate_of_fire"],
  tier: ["tier"], id: ["game_id"], faction: ["faction"], time: ["construction_time"], depth: ["tree_depth", "assembly_depth"], parts: ["part_count"], mass: ["mass"], cargo: ["cargo_capacity"],
};
